sudo: required
services:
  - docker

before_install:
  - docker --version

install:
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} -f .docker/Dockerfile .

script:
  - docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} yarn lint