sudo: required
services:
  - docker

before_install:
  - docker --version

install:
  - docker build -t friendlybot:latest .

script:
  - docker run -v $(pwd):/home/node/app -v /home/node/app/node_modules friendlybot:latest yarn lint
  - docker run -v $(pwd):/home/node/app -v /home/node/app/node_modules friendlybot:latest yarn test