sudo: required
services:
  - docker

before_install:
  - docker --version

install:
  - docker build -t friendlybot:latest -f .docker/Dockerfile .

script:
  - docker run -v $(pwd):/home/node/app friendlybot:latest yarn lint